name: Check Repo Setup

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  check-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests PyGithub pyyaml

      - name: Run Check Repo Setup Script
        run: |
          python scripts/check_repo_setup.py --yaml-file config/repos.yml --token ${{ secrets.GITHUB_TOKEN }} --owner ${{ secrets.REPO_OWNER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
